""" Add status column to user Migration

Revision ID: 21df6c566fbe
Revises: b1f4d01c504c
Create Date: 2020-10-01 08:13:09.239893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21df6c566fbe'
down_revision = 'b1f4d01c504c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
