""" Sale Model Migration

Revision ID: 25ff67a115a0
Revises: 5d57fbfd8422
Create Date: 2020-09-30 21:13:21.780479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ff67a115a0'
down_revision = '5d57fbfd8422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('sale_quantity', sa.Integer(), nullable=True),
    sa.Column('sale_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    # ### end Alembic commands ###
