""" Sale Model add sale amount column Migration

Revision ID: 4e7e9b3d7b07
Revises: 25ff67a115a0
Create Date: 2020-09-30 21:45:21.829260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e7e9b3d7b07'
down_revision = '25ff67a115a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('sale_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'sale_amount')
    # ### end Alembic commands ###
