"""OrderReceived Model Migration

Revision ID: 5d57fbfd8422
Revises: 9bc8ce9c9294
Create Date: 2020-09-30 20:10:34.516929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d57fbfd8422'
down_revision = '9bc8ce9c9294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordersreceived',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('order_quantity', sa.Integer(), nullable=True),
    sa.Column('order_payment', sa.String(length=255), nullable=True),
    sa.Column('order_total_amount', sa.Integer(), nullable=True),
    sa.Column('order_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordersreceived')
    # ### end Alembic commands ###
