"""Initial Migration

Revision ID: 7358b6fd7677
Revises: 
Create Date: 2020-10-01 09:16:05.952057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7358b6fd7677'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('product_stock', sa.Integer(), nullable=True),
    sa.Column('product_spoilt', sa.Integer(), nullable=True),
    sa.Column('product_buying_price', sa.Integer(), nullable=True),
    sa.Column('product_selling_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('profile_pic_path', sa.String(), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('pass_secure', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ordersreceived',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('order_quantity', sa.Integer(), nullable=True),
    sa.Column('order_payment', sa.String(length=255), nullable=True),
    sa.Column('order_total_amount', sa.Integer(), nullable=True),
    sa.Column('order_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productrequests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('request_quantity', sa.Integer(), nullable=True),
    sa.Column('request_status', sa.String(length=255), nullable=True),
    sa.Column('request_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('sale_quantity', sa.Integer(), nullable=True),
    sa.Column('sale_amount', sa.Integer(), nullable=True),
    sa.Column('sale_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    op.drop_table('productrequests')
    op.drop_table('ordersreceived')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
