""" ProductRequest Migration

Revision ID: b1f4d01c504c
Revises: 4e7e9b3d7b07
Create Date: 2020-10-01 07:24:31.452063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f4d01c504c'
down_revision = '4e7e9b3d7b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productrequests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('request_quantity', sa.Integer(), nullable=True),
    sa.Column('request_status', sa.String(length=255), nullable=True),
    sa.Column('request_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productrequests')
    # ### end Alembic commands ###
